### ISSUE TITLE
1.18.1 Update?

### ISSUE THREAD

**Issue by Darkosto** [nevoka-be/BringBackBedrock#1]
Hey!

Would you be able to port this to 1.18.1 and add a feature to generate bedrock both at the bottom of the world and the top? Currently, we're having a problem due to a minecraft bug that carves out the bedrock at the top of our world. There's not a way to fix it without using a mod that comes through on the final generation pass to replace the missing blocks.

Thank you very much!
Darkosto

**Comment by JayJay1989** [comment]
Done: [Curseforge](https://www.curseforge.com/minecraft/mc-mods/bring-back-bedrock/files/3570868)
